### ISSUE TITLE
subdirectory doesnt work.

### ISSUE THREAD

**Issue by Qwe2390** [leemahoney3/whmcs-client-password-changer#2]
Still not working in a sub directory when pressing change password it redirects you to standart domain.com/admin

**Comment by leemahoney3** [comment]
Hi Qwe,

Have you installed the latest version? v1.0.5

**Comment by Qwe2390** [comment]
Yes i did it its the latest one
________________________________
Gönderen: Lee Mahoney ***@***.***>
Gönderildi: 28 Aralık 2022 Çarşamba 19:03
Kime: leemahoney3/whmcs-client-password-changer ***@***.***>
Bilgi: Ilker Özel ***@***.***>; Author ***@***.***>
Konu: Re: [leemahoney3/whmcs-client-password-changer] subdirectory doesnt work. (Issue #2)


Hi Qwe,

Have you installed the latest version? v1.0.5

**Comment by leemahoney3** [comment]
Hi Qwe,

Can you please email me temporary logins (and login link for your admin area) to check this as I cannot replicate. My email is lee@leemahoney.dev.

If you would prefer not to send the logins via email, please create an admin account under my email address and ensure the ability for admins to reset their passwords is switched on.

**Comment by Qwe2390** [comment]
https://youtu.be/FnOJK_j4QsU here is a video so you can see that it doesnt work.

**Comment by leemahoney3** [comment]
Thank you, this should be fixed now in v1.0.6.
